### ISSUE TITLE
Display appropriate message when user isn't part of an organization

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gitea-react-toolkit#35]
As a user of GRT I want to know why I can't continue and what to do about it if I'm not part of an organization.

Proposal:
Line 1- Login not completed.
line 2- tc-Create cannot log you in until you are a part of an organization. To connect to an existing organization, contact your tech support team.

**DoD**: When a user without an organization attempts to login, they receive a message that informs them about the need for an organization.

**Comment by elsylambert** [comment]
Proposed Message:
Line 1- Login not completed.
line 2- You are not part of an Organization. To connect to an existing Organization, contact Link(@link to administrators ?@jag3773 ).
To add a new Organization , go to link(DCS link to create a new Organization)

**Comment by jag3773** [comment]
So are we requiring that a user be part of a DCS organization?

There is no global admin for organizations.  If someone knows of an organization that they want to join they would need to contact the owner of that that particular organization.

**Comment by ancientTexts-net** [comment]
https://app.zenhub.com/workspaces/uw---all-57a4b0551bff6d0c6f35e8eb/issues/unfoldingword/tc-create-app/132

**Comment by ancientTexts-net** [comment]
#tc-create-app/132

**Comment by ancientTexts-net** [comment]
tc-create-app/#132

**Comment by ancientTexts-net** [comment]
unfoldingword/tc-create-app/#132

**Comment by ancientTexts-net** [comment]
Now the RCL has a **tentative** error message.
Team says fine for now - but possible to change later

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/bd0dd825-ecb6-4bc3-9d99-75df818b9b52)

**Comment by klappy** [comment]
Issue is testable in Gitea React Toolkit: via `1.1.0-rc.1`
https://gitea-react-toolkit.netlify.app/#/Organization%20

Issue is implemented and testable in App: via `0.9.0-rc.4`
https://develop--tc-create-app.netlify.app/

**Comment by elsylambert** [comment]
Verified in 0.9.0-rc.4. When a user who does not have an Organization logs in, gets the message on the Organization page that the user is not part of any Organization.

Issue 1: Does not tell the user what to do next or how can the user be part of an organization.
Issue 2: User can still see uW Resources list and get to the files page to see the files listed. However the files cannot be opened and spinner goes on forever. This issue should be fixed by tc-create#145 when the user is blocked on stepper view based on the valid login.

@birchamp Needs decision if this one goes into Sprint Review tomorrow, as the functionality is not implemented fully at this point.

**Comment by elsylambert** [comment]
Needs regression for 1.0

**Comment by BincyJ** [comment]
@birchamp this was demoed and can be closed. Let me know if otherwise.
